using System;
using System.Collections.Generic;

namespace OnePieceTcg.Engine.Puzzles
{
    /// <summary>
    /// Player-facing catalog. Seeds are admitted offline only after the exact solver and selective-decision
    /// audit both pass. Runtime does no expensive batch solving: it constructs one fresh state on demand,
    /// while GameManager shuffles the 500 lightweight entries whenever Puzzle Mode is opened.
    ///
    /// Five proof-preserving card variants of each mechanic graph lead the manifest. The remaining positions are
    /// database-varied combat
    /// trees covering exact DON allocation, blocker removal, counter/card-floor pressure, Life-to-hand order,
    /// Double Attack, Rush, and multiple walls. Safe card substitutions come from the complete CardData library
    /// and preserve the full gameplay signature used during certification; effect-bearing cards never cross IDs.
    /// </summary>
    public static class CertifiedPuzzleCatalog
    {
        public const int TargetCount = 500;
        public const int CertificationVersion = 2;

        // Generated by: dotnet run -c Release --project Tools/Sim/Sim.csproj --
        //               puzzlequalityscan <range> <target> <startSeed>
        // Every seed below passed PuzzleQualityAnalyzer with >=2 consequential decisions and no unresolved
        // alternative counted as a loss.
        public static readonly int[] VerifiedSeeds =
        {
            2, 3, 10, 12, 17, 18, 21, 24, 26, 27, 28, 29, 30, 31, 32, 39, 41, 42, 43, 45, 48, 49, 59, 61, 63,
            66, 67, 73, 80, 81, 83, 84, 93, 97, 99, 101, 102, 103, 108, 111, 115, 122, 123, 129, 130, 137, 152,
            153, 159, 163, 165, 171, 172, 173, 174, 176, 180, 183, 186, 187, 189, 192, 194, 197, 198, 199, 200,
            203, 204, 206, 211, 212, 214, 217, 218, 226, 227, 228, 235, 237, 238, 247, 251, 252, 254, 259, 261,
            1002, 1005, 1006, 1007, 1012, 1015, 1018, 1019, 1023, 1024, 1025, 1028, 1040, 1042, 1044, 1046,
            1049, 1052, 1053, 1055, 1059, 1066, 1068, 1069, 1070, 1072, 1073, 1074, 1075, 1078, 1081, 1082,
            1083, 1087, 1088, 1089, 1094, 1097, 1098, 1099, 1102, 1105, 1106, 1107, 1110, 1112, 1117, 1119,
            1120, 1122, 1123, 1126, 1127, 1131, 1133, 1134, 1137, 1138, 1141, 1142, 1144, 1145, 1147, 1155,
            1157, 1159, 1160, 1162, 1168, 1169, 1174, 1175, 1181, 1182, 1183, 1184, 1185, 1187,
            2001, 2002, 2004, 2005, 2014, 2015, 2016, 2020, 2030, 2032, 2035, 2044, 2049, 2050, 2053, 2054,
            2059, 2067, 2068, 2073, 2074, 2077, 2081, 2083, 2086, 2089, 2092, 2093, 2094, 2095, 2097, 2099,
            2103, 2104, 2106, 2107, 2110, 2113, 2118, 2119, 2126, 2131, 2133, 2138, 2139, 2141, 2147, 2148,
            2154, 2158, 2159, 2163, 2165, 2170, 2172, 2173, 2175, 2181, 2183, 2184, 2185, 2189, 2194, 2195,
            2201, 2203, 2205, 2208, 2213, 2217, 2219, 2230, 2231, 2232, 2233, 2234, 2239, 2241, 2242, 2243,
            2245, 2246, 2251, 2252, 2254, 2255, 2258, 2259, 2260, 2261, 2266, 2269, 2275, 2276, 2277, 2278,
            2283, 2285, 2292,
            3001, 3004, 3006, 3009, 3013, 3014, 3015, 3016, 3017, 3019, 3020, 3021, 3023, 3024, 3026, 3030,
            3031, 3036, 3039, 3040, 3041, 3045, 3048, 3051, 3052, 3056, 3057, 3061, 3062, 3067, 3070, 3072,
            3074, 3079, 3080, 3081, 3083, 3084, 3085, 3088, 3093, 3094, 3096, 3100, 3101, 3102, 3109, 3111,
            3112, 3117, 3118, 3120, 3121, 3127, 3128, 3131, 3135, 3143, 3146, 3147, 3155, 3159, 3173, 3177,
            3178, 3182, 3183, 3184, 3185, 3186, 3188, 3189, 3190, 3191, 3195, 3198, 3209, 3210, 3211, 3212,
            3214, 3218, 3220, 3223, 3225, 3226, 3229, 3230, 3231, 3233, 3234, 3236, 3238, 3239, 3240, 3243,
            502, 508, 510, 512, 514, 516, 517, 520, 522, 525, 526, 531, 533, 537, 539, 541, 543, 547, 548, 549,
            554, 555, 559, 564, 565,
            1501, 1502, 1512, 1516, 1518, 1519, 1520, 1527,
            2501, 2503, 2506, 2508, 2509, 2514, 2516, 2518, 2520, 2521, 2530, 2533, 2535, 2536, 2540, 2542,
            2544, 2550, 2551, 2555, 2559, 2560, 2562, 2563, 2569,
            3503, 3504, 3505, 3506, 3509, 3510, 3513, 3515, 3516, 3518, 3520, 3522, 3525, 3528, 3530, 3533,
            3538, 3540, 3541, 3542, 3544, 3547, 3549, 3550, 3551,
            4004, 4005, 4011, 4012, 4013, 4016, 4017, 4018, 4019, 4020, 4022,
            5002, 5003, 5007, 5008, 5009, 5010, 5013, 5023, 5025, 5027, 5029, 5036, 5039, 5040, 5041, 5049,
            5052, 5053, 5054, 5055, 5066,
        };

        // Family-targeted follow-up pass. These replace 39 DON-split and 38 counter-floor seeds from the broad
        // sweep so a shuffled session cannot be dominated by the two easiest-to-generate structures.
        private static readonly int[] DiversitySeeds =
        {
            6106, 6115, 6118, 6122, 6126, 6143, 6151, 6224, 6330, 6334, 6478, 6500, 6519, 6581, 6604, 6675,
            6678, 6713, 6715, 6727, 6776, 6779, 6799, 6830, 6847,
            8038, 8106, 8121, 8170, 8178, 8206, 8209, 8243, 8291, 8298, 8342, 8433,
            9019, 9068, 9105, 9150, 9162, 9199, 9245, 9260, 9265, 9280, 9287, 9299, 9310, 9345, 9425,
            7084, 7088, 7126, 7135, 7171, 7227, 7305, 7345, 7361, 7427, 7454, 7494, 7503, 7515, 7535, 7617,
            7626, 7684, 7745, 7799, 7821, 7826, 7869, 7925, 7939,
        };

        public static List<AuthoredPuzzle> All()
        {
            var all = new List<AuthoredPuzzle>(TargetCount);
            foreach (var mechanic in MechanicPuzzleLibrary.All())
                for (int variant = 0; variant < 5; variant++)
                    all.Add(MechanicVariant(mechanic, variant));
            foreach (int seed in RebalancedSeeds()) all.Add(FromSeed(seed));
            if (all.Count != TargetCount)
                throw new InvalidOperationException(
                    $"Certified puzzle catalog has {all.Count} entries; expected {TargetCount}.");
            return all;
        }

        private static IEnumerable<int> RebalancedSeeds()
        {
            int dropDonPush = 39;
            int dropCounterPump = 38;
            foreach (int seed in VerifiedSeeds)
            {
                string category = PuzzleGenerator.Build(seed).Category;
                if (category == "don-push" && dropDonPush-- > 0) continue;
                if (category == "counter-pump" && dropCounterPump-- > 0) continue;
                yield return seed;
            }
            foreach (int seed in DiversitySeeds) yield return seed;
        }

        private static AuthoredPuzzle MechanicVariant(AuthoredPuzzle source, int variant)
        {
            int varietySeed = unchecked(0x51ED270B + StableHash(source.Id) * 31 + variant);
            var grade = PuzzleDifficultyGrader.Authored(source.Category);
            return new AuthoredPuzzle
            {
                Id = $"{source.Id}-v{variant + 1}",
                Title = source.Title,
                Attacker = source.Attacker,
                Category = source.Category,
                Teaches = source.Teaches,
                Difficulty = grade.Tier,
                DifficultyScore = grade.Score,
                DifficultyEvidence = grade.Evidence,
                PlayerTurnLimit = source.PlayerTurnLimit,
                Objective = source.Objective,
                Mechanics = source.Mechanics,
                Build = () => PuzzleCardCapabilities.ApplySafeVariety(source.Build(), varietySeed),
            };
        }

        private static AuthoredPuzzle FromSeed(int seed)
        {
            var metadata = PuzzleGenerator.Build(seed);
            string[] mechanics = MechanicsFor(metadata.Category);
            var grade = PuzzleDifficultyGrader.Generated(seed, metadata.Category);
            return new AuthoredPuzzle
            {
                Id = $"catalog-v{CertificationVersion}-{seed}",
                Title = metadata.Title,
                Attacker = metadata.AttackerSeat,
                Category = metadata.Category,
                Teaches = metadata.Teaches,
                Difficulty = grade.Tier,
                DifficultyScore = grade.Score,
                DifficultyEvidence = grade.Evidence,
                PlayerTurnLimit = 1,
                Objective = ObjectiveFor(metadata.Category),
                Mechanics = mechanics,
                Build = () =>
                {
                    var generated = PuzzleGenerator.Build(seed);
                    return PuzzleCardCapabilities.ApplySafeVariety(
                        generated.State, unchecked(seed * 7919 + CertificationVersion));
                },
            };
        }

        private static string ObjectiveFor(string category)
        {
            switch (category)
            {
                case "counter-pump":
                    return "Win this turn without knowing which hidden card the opponent will spend as Counter.";
                case "combo-wall":
                    return "Win this turn through both a hidden Counter and the visible Blocker.";
                case "double-wall":
                    return "Win this turn through two visible Blockers.";
                case "double-strike":
                    return "Make the Double Attack connect and finish this turn.";
                case "rush-finisher":
                    return "Find the additional attack that does not begin on the board.";
                default:
                    return "Win this turn. Ordinary attacks alone do not preserve the forced win.";
            }
        }

        private static string[] MechanicsFor(string category)
        {
            switch (category)
            {
                case "don-push":
                    return new[] { "DON!! allocation", "Counter floor", "Exact power thresholds" };
                case "blocker-break":
                    return new[] { "Blocker removal", "K.O. or rest", "Attack count" };
                case "counter-pump":
                    return new[] { "Hidden Counter", "Counter floor", "Card demand", "DON!! allocation" };
                case "combo-wall":
                    return new[] { "Blocker removal", "Hidden Counter", "Resource sequencing", "Attack order" };
                case "double-strike":
                    return new[] { "Double Attack", "Blocker removal", "Damage sequencing" };
                case "rush-finisher":
                    return new[] { "Rush", "Develop then attack", "DON!! budgeting" };
                case "double-wall":
                    return new[] { "Multiple Blockers", "Multiple removal effects", "Resource sequencing" };
                default:
                    return new[] { "Forced lethal" };
            }
        }

        private static int StableHash(string value)
        {
            unchecked
            {
                int hash = 17;
                foreach (char c in value ?? "") hash = hash * 31 + c;
                return hash;
            }
        }
    }
}
